
version: '3.7'
x-volumes:
  &vol-localtime
  type: bind
  source: /etc/localtime
  target: /etc/localtime
  read_only: true
services:
  postfix:
    build:
      context: ./
      dockerfile: ./postfix/Dockerfile
    image: mailbond-postfix:01
    container_name: mailbond-postfix
    volumes:
      - type: volume
        source: mailbox
        target: /var/mail
      - *vol-localtime
    networks:
      - mailbond-bridge
  dovecot:
    build:
      context: ./
      dockerfile: ./dovecot/Dockerfile
    image: mailbond-dovecot:01
    container_name: mailbond-dovecot
    volumes:
      - type: volume
        source: mailbox
        target: /var/mail
      - *vol-localtime
    networks:
      - mailbond-bridge
    depends_on:
      - postfix
networks:
  mailbond-bridge:
    driver: bridge
volumes:
  mailbox:
